#!/usr/bin/env node
/*
  Bundle @rolemodel/optics into a single browser-loadable stylesheet at
  vendor/optics.css (reset + tokens + base + layout + utilities + all
  components). Dependency-free: inlines Optics' PostCSS-style @import graph by
  hand (file dir -> src root -> node_modules), hoisting remote @import url(...)
  to the top because CSS ignores non-leading @import.

  Usage: node tools/build-optics.js [path-to-optics-checkout]
  Default source: ../optics (sibling checkout of the Optics repo).
*/
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const OPTICS = path.resolve(process.argv[2] || path.join(REPO, '..', 'optics'));
const SRC = path.join(OPTICS, 'src');
const NM = path.join(OPTICS, 'node_modules');
const ENTRY = path.join(SRC, 'optics.css');
const OUT = path.join(REPO, 'vendor', 'optics.css');

if (!fs.existsSync(ENTRY)) {
  console.error(`Optics source not found at ${ENTRY}.\n` +
    `Pass the path to an Optics checkout: node tools/build-optics.js <path>`);
  process.exit(1);
}

const seen = new Set();
const remotes = [];

function tryPaths(base) {
  for (const c of [base, base + '.css', path.join(base, 'index.css')]) {
    if (fs.existsSync(c) && fs.statSync(c).isFile()) return c;
  }
  return null;
}

function resolve(spec, fromDir) {
  const roots = (spec.startsWith('.') || spec.startsWith('/'))
    ? [path.resolve(fromDir, spec)]
    : [path.join(fromDir, spec), path.join(SRC, spec), path.join(NM, spec)];
  for (const base of roots) {
    const r = tryPaths(base);
    if (r) return r;
  }
  return null;
}

function inline(file) {
  if (seen.has(file)) return '';
  seen.add(file);
  const dir = path.dirname(file);
  const css = fs.readFileSync(file, 'utf8');
  // Capture the full quoted spec; the value may contain ';' (e.g. the Google
  // Fonts URL's `wght@…900;1,…`), so match between matching quotes, not up to ';'.
  return css.replace(
    /@import\s+(?:url\(\s*)?(['"])(.*?)\1\s*\)?\s*;/g,
    (m, _q, spec) => {
      spec = spec.trim();
      if (/^https?:/i.test(spec)) { remotes.push(spec); return ''; }
      const r = resolve(spec, dir);
      if (!r) { console.error('UNRESOLVED @import:', spec, 'in', file); return m; }
      return inline(r);
    });
}

const pkg = JSON.parse(fs.readFileSync(path.join(OPTICS, 'package.json'), 'utf8'));
const body = inline(ENTRY);
const header = [...new Set(remotes)].map((u) => `@import url('${u}');`).join('\n');
const banner =
  `/* Bundled from ${pkg.name} v${pkg.version} (src/optics.css) — reset + ` +
  `tokens + base + layout + utilities + all components.\n` +
  `   Generated by tools/build-optics.js; do not edit by hand. */\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, banner + (header ? header + '\n\n' : '') + body);
console.log(`wrote ${OUT} (${fs.statSync(OUT).size} bytes) from ${pkg.name} v${pkg.version}`);
